apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
type: Opaque
stringData:
  DB_HOST: "<your-rds-endpoint>"
  DB_USER: "<dbuser>"
  DB_PASS: "<dbpassword>"
  DB_NAME: "appdb"
